### ISSUE TITLE
사용자 매뉴얼 개선 요청

### ISSUE THREAD

**Issue by swbyun** [experdb/eXperDB-DB2PG#14]
사용자 매뉴얼 개선 요청드립니다.

**Comment by joo01224** [comment]
네 개선하겠습니다~

**Comment by gampol** [comment]
공개용 이관툴을 찾는중에 여기까지 왔네요.ㅎㅎ 
사용자 매뉴얼(PDF) 파일은 현행화된 버전은 찾을 수 가 없군요. 메인에 링크된 카페에서 받긴하였으나 
이전 버전용 같습니다. 아니면 제가 잘못 받은것일 수 있구요. 

버그 있어 개선 부탁드리겠습니다.
MetaExtractMapper.xml파일에 오라클(ORA), 티베로(TBR)  쿼리중(getConstraintInform ) 
SQL Error [21000]: JDBC-11002:Subquery returned multiple rows where a scalar value was expected.
에러 발생으로 확인해 보니 
.... (SELECT INDEX_TYPE FROM ALL_INDEXES WHERE INDEX_NAME = UC.INDEX_NAME)
구문에 DBMS 단일 계정을 사용한다면 문제없으나 여러 계정의 같은 형태의 DB 구조라면(계정별 동일 명칭의 테이블명)
문제가 발생하네요.
(SELECT INDEX_TYPE FROM ALL_INDEXES WHERE INDEX_NAME = UC.INDEX_NAME **AND OWNER = UC.OWNER**)
수정 필요해 보입니다.

공개해 주셔서 감사하고 잘 사용하겠습니다.
