### ISSUE TITLE
PgSQL 의 컬럼의 순서나 중간에 추가가 된다면 문제가 있군요.?

### ISSUE THREAD

**Issue by gampol** [experdb/eXperDB-DB2PG#61]
속도를 위해서 그랬는지 모르겠네요.?
소스 확인해 보니 COPY  IN 으로 되어 있는거 보니 덤프된 데이터를 그대로 pgsql에 밀어 넣는 형식인것 같습니다.?
헌데 이게 제가 테스트 중에 있는 작업에 치명적인 단점이 되었네요..
기존 테이블 구조에서 pgsql 추가적으로 중간 중간 컬럼 추가와 삭제가 있는데 이관시 문제가 발생하군요.
제가 작업하는 기간에 적용은 불가하겠지만 시간을 두고서라도 보완이 되었으면 정말 좋겠습니다.
(아니면 다른 방법이 있을까요? queries.xml 파일에 컬럼순서로 처리하면 가능할지...)

추가합니다.
소스 변경하여 처리토록 하였는데 문제 없는지 모르겠네요.ㅎㅎ

DBWriter.java
List<String> columnNames; //전역변수 추가 
public DBWriter(String poolName, List<String> columnNames) // 생성자 파라미터 추가
public void DBWrite(String lineStr, String table_nm) // COPY 처리문 수정
         String columns = String.join(",", columnNames);
         copyIn = copyManager.copyIn("COPY " + ConfigInfo.TAR_DB_CONFIG.SCHEMA_NAME + "." + table_nm + "("+ columns +") FROM STDIN" + strCopyOptions);

ExecuteDataTransfer.java
new DBWriter(.., columnNames)  // 추가

이런식으로 수정해보니 현재는 문제 없는거 같습니다.

**Comment by swbyun** [comment]
pull request 보내주시면 검토해 보겟습니다.

**Comment by swbyun** [comment]
적용완료
