### ISSUE TITLE
db2 error

### ISSUE THREAD

**Issue by ujangja** [experdb/eXperDB-DB2PG#91]
always got this error when source db type is DB2
is it hardcoded to oracle?

Nov 04, 2022 10:28:30 AM oracle.jdbc.driver.OracleDriver registerMBeans
WARNING: Error while registering Oracle JDBC Diagnosability MBean.
java.lang.StackOverflowError
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)

**Comment by swbyun** [comment]
db2 What kind of work did you do, ddl output?, migration?

It is not hardcoded in Oracle. Please use the latest release file.

**Comment by swbyun** [comment]
issue complete
